//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BellSupportSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportTicket
    {
        public int SupportTicketID { get; set; }
        public string ProjectName { get; set; }
        public string DateTimeReceived { get; set; }
        public string Department { get; set; }
        public string RequestedBy { get; set; }
        public string Description { get; set; }
    }
}
